In [1]:
from sklearn.datasets import load_iris

In [2]:
iris = load_iris()
X = iris.data
y = iris.target
print(X)
print(y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [3]:
from tensorflow.keras.layers import Conv2D, Dense, Flatten, MaxPool2D
from tensorflow.keras.utils import to_categorical

In [4]:
y = to_categorical(y)

# Wequential 클래스 활용, 1번 히든 레이어 16개 노드 구성, 출력층에 클래스에 맞게 노드 구성

In [5]:
from tensorflow.keras.models import Sequential
from tensorflow.keras import optimizers

### softmax  
- 세 개 이상으로 분류하는 다중 클래스 분류에서 사용되는 활성화 함수  
- 분류될 클래스가 n개라 할 때, n차원의 벡터를 입력받아, 각 클래스에 속할 확률을 추정

In [6]:
model = Sequential()
model.add(Dense(16, input_dim=4, activation = 'relu'))
model.add(Dense(3,activation = 'softmax'))
model.compile(optimizer='nadam', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(X,y, epochs=100, batch_size=1)


Epoch 1/100
150/150 [==============================] - 1s 870us/step - loss: 1.3756 - accuracy: 0.2800
Epoch 2/100
150/150 [==============================] - 0s 1ms/step - loss: 0.8878 - accuracy: 0.5933
Epoch 3/100
150/150 [==============================] - 0s 1ms/step - loss: 0.7264 - accuracy: 0.7267
Epoch 4/100
150/150 [==============================] - 0s 877us/step - loss: 0.6287 - accuracy: 0.7667
Epoch 5/100
150/150 [==============================] - 0s 850us/step - loss: 0.5664 - accuracy: 0.7600
Epoch 6/100
150/150 [==============================] - 0s 850us/step - loss: 0.5167 - accuracy: 0.8400
Epoch 7/100
150/150 [==============================] - 0s 837us/step - loss: 0.4776 - accuracy: 0.8867
Epoch 8/100
150/150 [==============================] - 0s 930us/step - loss: 0.4449 - accuracy: 0.9200
Epoch 9/100
150/150 [==============================] - 0s 930us/step - loss: 0.4157 - accuracy: 0.8867
Epoch 10/100
150/150 [==============================] - 0s 1ms/step - loss: 0

150/150 [==============================] - 0s 1ms/step - loss: 0.0752 - accuracy: 0.9733
Epoch 81/100
150/150 [==============================] - 0s 1ms/step - loss: 0.0719 - accuracy: 0.9667
Epoch 82/100
150/150 [==============================] - 0s 1ms/step - loss: 0.0754 - accuracy: 0.9733
Epoch 83/100
150/150 [==============================] - 0s 1ms/step - loss: 0.0702 - accuracy: 0.9800
Epoch 84/100
150/150 [==============================] - 0s 1ms/step - loss: 0.0749 - accuracy: 0.9733
Epoch 85/100
150/150 [==============================] - 0s 1ms/step - loss: 0.0802 - accuracy: 0.9533
Epoch 86/100
150/150 [==============================] - 0s 1ms/step - loss: 0.0808 - accuracy: 0.9667
Epoch 87/100
150/150 [==============================] - 0s 1ms/step - loss: 0.0700 - accuracy: 0.9800
Epoch 88/100
150/150 [==============================] - 0s 1ms/step - loss: 0.0726 - accuracy: 0.9733
Epoch 89/100
150/150 [==============================] - 0s 1ms/step - loss: 0.0722 - accuracy: 

In [7]:
model = Sequential()
model.add(Dense(8, input_dim=4, activation = 'relu'))
model.add(Dense(3,activation = 'softmax'))
model.compile(optimizer='nadam', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(X,y, epochs=100, batch_size=1)

Epoch 1/100
150/150 [==============================] - 1s 1ms/step - loss: 1.2341 - accuracy: 0.2800
Epoch 2/100
150/150 [==============================] - 0s 1ms/step - loss: 1.0637 - accuracy: 0.5733
Epoch 3/100
150/150 [==============================] - 0s 1ms/step - loss: 0.9749 - accuracy: 0.6533
Epoch 4/100
150/150 [==============================] - 0s 870us/step - loss: 0.8952 - accuracy: 0.5933
Epoch 5/100
150/150 [==============================] - 0s 1ms/step - loss: 0.8165 - accuracy: 0.6600
Epoch 6/100
150/150 [==============================] - 0s 1ms/step - loss: 0.7443 - accuracy: 0.6600
Epoch 7/100
150/150 [==============================] - 0s 884us/step - loss: 0.6854 - accuracy: 0.6733
Epoch 8/100
150/150 [==============================] - 0s 877us/step - loss: 0.6316 - accuracy: 0.7333
Epoch 9/100
150/150 [==============================] - 0s 884us/step - loss: 0.5865 - accuracy: 0.8133
Epoch 10/100
150/150 [==============================] - 0s 843us/step - loss: 0.545

150/150 [==============================] - 0s 1ms/step - loss: 0.0873 - accuracy: 0.9667
Epoch 81/100
150/150 [==============================] - 0s 984us/step - loss: 0.0856 - accuracy: 0.9733
Epoch 82/100
150/150 [==============================] - 0s 863us/step - loss: 0.0845 - accuracy: 0.9800
Epoch 83/100
150/150 [==============================] - 0s 950us/step - loss: 0.0842 - accuracy: 0.9733
Epoch 84/100
150/150 [==============================] - 0s 904us/step - loss: 0.0847 - accuracy: 0.9667
Epoch 85/100
150/150 [==============================] - 0s 870us/step - loss: 0.0829 - accuracy: 0.9800
Epoch 86/100
150/150 [==============================] - 0s 857us/step - loss: 0.0851 - accuracy: 0.9733
Epoch 87/100
150/150 [==============================] - 0s 944us/step - loss: 0.0824 - accuracy: 0.9733
Epoch 88/100
150/150 [==============================] - 0s 971us/step - loss: 0.0789 - accuracy: 0.9667
Epoch 89/100
150/150 [==============================] - 0s 877us/step - loss: 0

## CNN(Convolutional Neural Network)

In [21]:
from tensorflow.keras.layers import Conv2D, Dense, Flatten, InputLayer,MaxPool2D
from tensorflow.keras.datasets import mnist

import numpy as np

In [9]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [10]:
X_train = X_train.astype('float32') / 255
X_test = X_test.astype('float32') / 255

In [11]:
X_train = np.expand_dims(X_train, -1)
X_test = np.expand_dims(X_test, -1)

In [12]:
print(X_train.shape[0])
print(X_test.shape[0])

60000
10000


In [13]:
np.unique(y_train)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [14]:
# 차원을늘림
y_train = to_categorical(y_train, num_classes=10)
y_test = to_categorical(y_test, num_classes=10)

In [15]:
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [24]:
model = Sequential()
# 영상에 맞춰서 input을 구성 
model.add(Input(shape=(28,28,1)))
model.add(Conv2D(6, kernel_size = (3, 3), activation='relu'))
#하나하나의 픽셀을 feature로 보고 일차원으로 나열 함
model.add(Flatten())

model.add(Dense(10, activation = 'softmax'))

model.summary()

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_4 (Conv2D)            (None, 26, 26, 6)         60        
_________________________________________________________________
flatten_4 (Flatten)          (None, 4056)              0         
_________________________________________________________________
dense_8 (Dense)              (None, 10)                40570     
Total params: 40,630
Trainable params: 40,630
Non-trainable params: 0
_________________________________________________________________


In [17]:
X_train[0].shape

(28, 28, 1)

In [26]:
model.compile(loss = 'categorical_crossentropy', optimizer = 'adam',metrics=['accuracy'])
model.fit(X_train, y_train, batch_size = 128, epochs = 15, validation_split=0.2)

Epoch 1/15
375/375 [==============================] - 5s 12ms/step - loss: 0.4365 - accuracy: 0.8812 - val_loss: 0.2669 - val_accuracy: 0.9217
Epoch 2/15
375/375 [==============================] - 4s 12ms/step - loss: 0.2383 - accuracy: 0.9323 - val_loss: 0.1947 - val_accuracy: 0.9486
Epoch 3/15
375/375 [==============================] - 5s 12ms/step - loss: 0.1725 - accuracy: 0.9516 - val_loss: 0.1470 - val_accuracy: 0.9599
Epoch 4/15
375/375 [==============================] - 5s 13ms/step - loss: 0.1345 - accuracy: 0.9626 - val_loss: 0.1267 - val_accuracy: 0.9652
Epoch 5/15
375/375 [==============================] - 5s 12ms/step - loss: 0.1129 - accuracy: 0.9680 - val_loss: 0.1142 - val_accuracy: 0.9685
Epoch 6/15
375/375 [==============================] - 4s 12ms/step - loss: 0.0961 - accuracy: 0.9731 - val_loss: 0.1046 - val_accuracy: 0.9700
Epoch 7/15
375/375 [==============================] - 5s 12ms/step - loss: 0.0849 - accuracy: 0.9765 - val_loss: 0.0987 - val_accuracy: 0.9712

In [27]:
score = model.evaluate(X_test, y_test, verbose=0)
print("Test loss:", score[0])
print("Test accuracy:", score[1])

Test loss: 0.07837679237127304
Test accuracy: 0.9751999974250793


## Pooling Layer  
- 출력 데이터의 크기를 줄이거나 특정 데이터를 강조하는 용도로 사용
- Max Pooling과 Average Pooning, Min Pooling이 있음
- 정사각 행렬의 특정 영역 안에 값의 최댓값을 모으거나 특정 영역의 평균을 구하는 방식으로 동작 
- 일반적으로 Pooing 크기와 Stride를 같은 크기로 설정하여 모든 원소가 한 번씩 처리 되도록 설정  
- CNN에서는 주로 Max Pooling을 사용  
  
    
    
- **Pooling 레이어, Convolution 레이어와 비교**
  
    - 학습대상 파라미터가 없음
    - Pooling 레이어를 통과하면 행렬의 크기 감소
    - Pooling 레이어를 통해서 채널 수 변경 없음


In [35]:
model = Sequential()
# 영상에 맞춰서 input을 구성 
model.add(Input(shape=(28,28,1)))
model.add(Conv2D(6, kernel_size = (3, 3), activation='relu'))
# pool_size가 크면 파라미터는 줄어듬, 정보 손실 가능성 커짐 
model.add(MaxPool2D(pool_size = (2,2)))
#하나하나의 픽셀을 feature로 보고 일차원으로 나열 함
model.add(Flatten())

model.add(Dense(10, activation = 'softmax'))

model.summary()

Model: "sequential_14"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_11 (Conv2D)           (None, 26, 26, 6)         60        
_________________________________________________________________
max_pooling2d_5 (MaxPooling2 (None, 13, 13, 6)         0         
_________________________________________________________________
flatten_9 (Flatten)          (None, 1014)              0         
_________________________________________________________________
dense_13 (Dense)             (None, 10)                10150     
Total params: 10,210
Trainable params: 10,210
Non-trainable params: 0
_________________________________________________________________


In [30]:
model.compile(loss = 'categorical_crossentropy', optimizer = 'adam',metrics=['accuracy'])
model.fit(X_train, y_train, batch_size = 128, epochs = 15, validation_split=0.2)

Epoch 1/15
375/375 [==============================] - 6s 15ms/step - loss: 0.6150 - accuracy: 0.8356 - val_loss: 0.2892 - val_accuracy: 0.9171
Epoch 2/15
375/375 [==============================] - 5s 13ms/step - loss: 0.2777 - accuracy: 0.9187 - val_loss: 0.2336 - val_accuracy: 0.9331
Epoch 3/15
375/375 [==============================] - 5s 14ms/step - loss: 0.2290 - accuracy: 0.9347 - val_loss: 0.2009 - val_accuracy: 0.9466
Epoch 4/15
375/375 [==============================] - 6s 15ms/step - loss: 0.1958 - accuracy: 0.9437 - val_loss: 0.1756 - val_accuracy: 0.9535
Epoch 5/15
375/375 [==============================] - 6s 15ms/step - loss: 0.1706 - accuracy: 0.9514 - val_loss: 0.1563 - val_accuracy: 0.9578
Epoch 6/15
375/375 [==============================] - 5s 14ms/step - loss: 0.1519 - accuracy: 0.9564 - val_loss: 0.1408 - val_accuracy: 0.9622
Epoch 7/15
375/375 [==============================] - 5s 14ms/step - loss: 0.1350 - accuracy: 0.9618 - val_loss: 0.1278 - val_accuracy: 0.9658

## 프로젝트 시 남들이 구현해 놓은 걸 테스트용도로 사용해 보는 것도 ㄱㅊ

In [63]:
from tensorflow.keras.applications import ResNet101
conv_base = ResNet101(weights = 'imagenet', include_top= False, input_shape=(150,150,3))

171450368/171446536 [==============================] - 20s 0us/step


In [64]:
conv_base.summary()

Model: "resnet101"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_19 (InputLayer)           [(None, 150, 150, 3) 0                                            
__________________________________________________________________________________________________
conv1_pad (ZeroPadding2D)       (None, 156, 156, 3)  0           input_19[0][0]                   
__________________________________________________________________________________________________
conv1_conv (Conv2D)             (None, 75, 75, 64)   9472        conv1_pad[0][0]                  
__________________________________________________________________________________________________
conv1_bn (BatchNormalization)   (None, 75, 75, 64)   256         conv1_conv[0][0]                 
__________________________________________________________________________________________

In [ ]:
medel = Sequential()
model.add(conv_base)
model.add(Flatten())
model.add(Dense(256, activation = 'relu'))
model.add(Dense(1, activation='sigmoid'))

## RNN  
- 반복적이고 순차적인 데이터(Sequential data)학습에 특화된 인공신경망의 한 종류
- 음성 웨이브폼을 파악하거나, 텍스트의 앞 뒤 성분을 파악할 때 주로 사용
- 시간에 종속된다는 특징
- 현재 단어만 아니라 이전 단어에도 의존(<font color = 'red'>과거학습의 Weight를 통해 현재학습에 반영</font>)<p/>
- RNN 단점은 처음시작한 Weight의 값이 점차 학습이 될 수록 상쇄 된다는 것 ---> 이를 해결한 알고리즘이 LSIM(Long Short Term Memory Network)

### bidirectional  <p/>
![image](https://user-images.githubusercontent.com/59672592/127452677-308696e5-3e92-491a-a7f1-ae949521010a.png)  
양방향에서 weight를 받음